server {
    listen 80;

    server_name {{DOMAIN}} www.{{DOMAIN}};

    root {{DIST_PATH}};
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location = /favicon.ico {
        log_not_found off;
    }

    access_log /var/log/nginx/{{DOMAIN}}.access.log;
    error_log /var/log/nginx/{{DOMAIN}}.error.log;
}